# Ensure the main Prometheus server is exposed via ClusterIP
server:
  service:
    type: ClusterIP
  # Disable Ingress for the Prometheus server component directly
  ingress:
    enabled: false

# Ensure Alertmanager is exposed via ClusterIP
alertmanager:
  service:
    type: ClusterIP
  # Disable Ingress for the Alertmanager component directly
  ingress:
    enabled: false

# Ensure Grafana is exposed via ClusterIP
grafana:
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana"
  service:
    type: ClusterIP
  # Disable Ingress for the Grafana component directly
  ingress:
    enabled: false
  adminPasswordKey: admin-password
  adminPasswordSecret: grafana-admin-password
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# ServiceMonitors are fine as they are, they define how Prometheus scrapes
serviceMonitors:
  - name: backend-metrics
    namespace: default # Ensure this matches the namespace of your backend app
    selector:
      matchLabels:
        app: backend
    endpoints:
      - port: http # This should match the name of the port in your backend-service
        path: /metrics

        interval: 15s
