apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8-visualizer-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8-visualizer-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8-visualizer-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8-visualizer-role
subjects:
- kind: ServiceAccount
  name: k8-visualizer-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visual-img-deployment
  labels:
    app: visual-img
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visual-img
  template:
    metadata:
      labels:
        app: visual-img
    spec:
      containers:
      - name: visual-img
        image: shashank9928/visual-img:latest # Jenkins will update this tag
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: visual-img-service
spec:
  selector:
    app: visual-img
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
