# This ArgoCD Application will manage your application's ingress resource.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  project: default
  source:
    repoURL: https://github.com/shashank6613/TailWindApp.git
    targetRevision: feature
    path: K8s/Ingress/argo
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
