server:
  extraArgs:
    - --insecure
    - --basehref=/argocd
    - --rootpath=/argocd
  ingress:
    enabled: false

configs:
  params:
    server.insecure: true  # equivalent to spec.server.insecure in the operator CR

controller:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

applicationSet:
  enabled: true

notifications:
  enabled: true
