apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shashank6613/TailWindApp.git
    targetRevision: feature
    path: K8s/manifests  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    env:
      - name: ARGOCD_SERVER_BASE_HREF
        value: /argocd





