apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: app-clus
  region: us-west-2
  version: "1.32"

managedNodeGroups:
  - name: stand-work
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3

iam:
  withOIDC: true
