AWSTemplateFormatVersion: '2010-09-09'
Description: 'FOR us-west-2, CFN template for primary and replica PostgreSQL DB using default-SG and Subnet group & 1 EC2s'

Resources:
  EC2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: Project-Role-K8-Prof
      Roles:
        - Project-Role-K8
        
# EC2 Instance (Master)
  MasterInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: 'ami-03f8acd418785369b'  # Ubuntu 22.04 AMI  #us-west-2
      SubnetId: subnet-0277c5e7de9bdb839  #us-west-2a
      KeyName: linked     # For Oregon us-east-2
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroupIds:
        - sg-0a5a89c14bfd4e505    #us-west-2
      Tags:
        - Key: Name
          Value: 'Master'
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash
          curl -sL "https://twentyseventhbucket.s3.amazonaws.com/ec2-tool.sh" -o /tmp/ec2-tool.sh
          curl -sL "https://twentyseventhbucket.s3.amazonaws.com/check-versions.sh" -o /tmp/check-versions.sh
          chmod +x /tmp/ec2-tool.sh /tmp/check-versions.sh
          sudo /tmp/ec2-tool.sh

# DB Subnet Group for RDS Instances
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: 'Default DB Subnet Group'
      SubnetIds:
        - subnet-0277c5e7de9bdb839   #us-west-2a
        - subnet-00c57145bfe2258a0   #us-west-2b
        - subnet-09e11b6ccb343dee5  #us-west-2c

# Primary RDS PostgreSQL Database
  PrimaryRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: 'MyPrimaryPGDB'
      Engine: 'postgres'
      DBInstanceClass: 'db.t3.micro'
      AllocatedStorage: '20'
      MasterUsername: 'shank'
      MasterUserPassword: 'k8admin1234link'
      PubliclyAccessible: true
      DBParameterGroupName: 'newpara'
      VPCSecurityGroups:
        - sg-0a5a89c14bfd4e505    #us-west-2
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: 'false'
      DBName: 'primarydb'

# Replica RDS PostgreSQL Database
  ReplicaRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: 'MyReplicaPGDB'
      Engine: 'postgres'
      DBInstanceClass: 'db.t3.micro'
      AllocatedStorage: '20'
      PubliclyAccessible: true
      DBParameterGroupName: 'newpara'
      VPCSecurityGroups:
        - sg-0a5a89c14bfd4e505    #us-west-2
      MultiAZ: 'false'
      SourceDBInstanceIdentifier: !Ref PrimaryRDSInstance


Outputs:
  PrimaryDBEndpoint:
    Description: "The endpoint of the Primary RDS DB Instance"
    Value: !GetAtt PrimaryRDSInstance.Endpoint.Address
  
  ReplicaDBEndpoint:
    Description: "The endpoint of the Replica RDS DB Instance"
    Value: !GetAtt ReplicaRDSInstance.Endpoint.Address

  MasterInstanceId:
    Description: "Jenkins Master EC2 Instance ID"
    Value: !Ref MasterInstance