apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress
  namespace: default # This Ingress only manages services in this namespace
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Frontend application at root path
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          # Backend API
          - path: /app/api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5000
