apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8ui
  namespace: k8ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8ui-readonly
rules:
  - apiGroups: [""]
    resources: ["pods","pods/log","services","namespaces"]
    verbs: ["get","list","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments","replicasets","statefulsets","daemonsets"]
    verbs: ["get","list","watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","list","watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8ui-readonly-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8ui-readonly
subjects:
  - kind: ServiceAccount
    name: k8ui
    namespace: k8ui
